CREATE DATABASE MiniEcommerceStore;
USE MiniEcommerceStore;

CREATE TABLE CUSTOMER (
 CustomerID INT PRIMARY KEY AUTO_INCREMENT,
 Name VARCHAR(100),
 Email VARCHAR(100),
 Phone VARCHAR(20),
 Address TEXT,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADMIN (
 AdminID INT PRIMARY KEY AUTO_INCREMENT,
 Name VARCHAR(100),
 Email VARCHAR(100),
 Password VARCHAR(255)
);

CREATE TABLE CATEGORY (
 CategoryID INT PRIMARY KEY AUTO_INCREMENT,
 CategoryName VARCHAR(50)
);

CREATE TABLE SUBCATEGORY (
 SubCategoryID INT PRIMARY KEY AUTO_INCREMENT,
 CategoryID INT,
 SubCategoryName VARCHAR(100),
 FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

CREATE TABLE PRODUCT (
 ProductID INT PRIMARY KEY AUTO_INCREMENT,
 Name VARCHAR(100),
 SubCategoryID INT,
 Price DECIMAL(10,2),
 Description TEXT,
 Image_URL VARCHAR(255),
 Stock_Quantity INT,
 FOREIGN KEY (SubCategoryID) REFERENCES SUBCATEGORY(SubCategoryID)
);

CREATE TABLE CART (
 CartID INT PRIMARY KEY AUTO_INCREMENT,
 CustomerID INT,
 CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE CARTITEMS (
 CartItemID INT PRIMARY KEY AUTO_INCREMENT,
 CartID INT,
 ProductID INT,
 Quantity INT,
 FOREIGN KEY (CartID) REFERENCES CART(CartID),
 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE ORDERS (
 OrderID INT PRIMARY KEY AUTO_INCREMENT,
 CustomerID INT,
 Order_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
 TotalAmount DECIMAL(10,2),
 Status VARCHAR(50),
 Name VARCHAR(100),
 Phone VARCHAR(15),
 ShippingAddress TEXT,
 City VARCHAR(100),
 State VARCHAR(100),
 Pincode VARCHAR(10),
 FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE ORDERITEMS (
 OrderItemID INT PRIMARY KEY AUTO_INCREMENT,
 OrderID INT,
 ProductID INT,
 Quantity INT,
 Price DECIMAL(10,2),
 FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE PAYMENT (
 PaymentID INT PRIMARY KEY AUTO_INCREMENT,
 OrderID INT,
 PaymentDate DATETIME,
 PaymentMethod VARCHAR(50),
 PaymentStatus VARCHAR(50),
 Amount DECIMAL(10,2),
 FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);